# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PhychoLee's Blog
email: phycholee@qq.com

#baseurl: /phycholee.github.com 
description: "PhychoLee 三楼四楼" # this means to ignore newlines until "baseurl:"
    
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phycholee.github.com" 

header-img: http://osjs7p1js.bkt.clouddn.com/work.jpg

home-img: http://osjs7p1js.bkt.clouddn.com/home.jpg

github_username:  phycholee

# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important 


#分页
paginate: 10
#paginate_path: "posts/page:num"

#时区
timezone: Asia/Shanghai

highlighter: rouge
#permalink: pretty

gems: [jekyll-paginate]

all_categories: [
#  id     标题        URL            副标题            头图片
["java", "Java","/posts/java.html","Java笔记","http://osjs7p1js.bkt.clouddn.com/java.png"],
["spring", "Spring","/posts/spring.html","Spring笔记","http://osjs7p1js.bkt.clouddn.com/spring.png"],
["database", "Database","/posts/database.html","Database笔记","http://osjs7p1js.bkt.clouddn.com/database.png"],
["front", "前端开发","/posts/front.html","前端知识笔记","http://osjs7p1js.bkt.clouddn.com/front.jpg"], 
["android", "Android","/posts/android.html","Android笔记","http://osjs7p1js.bkt.clouddn.com/android.jpg"],
["news", "新闻","/posts/news.html","新闻热点","http://osjs7p1js.bkt.clouddn.com/news.jpg"], 
["todayTalk", "今日感想","/posts/todayTalk.html","记录生活随想","http://osjs7p1js.bkt.clouddn.com/notebook.jpg"],
["digital", "数码","/posts/digital.html","数码新潮","http://osjs7p1js.bkt.clouddn.com/digital.jpeg"]
]