# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PhychoLee's Blog
email: 962109025@qq.com

#baseurl: /phycholee.github.com
description: > # this means to ignore newlines until "baseurl:"
    
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phycholee.github.com" 

header-img: /assets/img/work.jpg

github_username:  phycholee

# Build settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


#分页
paginate: 8
#paginate_path: "posts/page:num"

#时区
timezone: Asia/Shanghai

highlighter: rouge
#permalink: pretty

gems: [jekyll-paginate]

all_categories: [
["front", "前端开发","/posts/front.html","前端知识笔记"], 
["java", "Java","/posts/java.html","Java笔记","/assets/img/java.png"],
["news", "新闻","/posts/news.html","新闻热点"], 
["todayTalk", "今日感想","/posts/todayTalk.html","记录生活随想","/assets/img/notebook.jpg"],
["digital", "数码","/posts/digital.html","数码新潮","/assets/img/digital.jpeg"]
]